experiment_name: bowl
checkpoint_path: DIF_decoder/logs/bowl/checkpoints/model.pth
num_instances: 801
latent_dim: 128
model_type: sine
hidden_num: 128
hyper_hidden_layers: 1
hyper_hidden_features: 256