batch_size: 1
epochs: 50
epochs_til_checkpoint: 5
eval_split: DIF_decoder/split/eval/bottle.txt
checkpoint_path: DIF_decoder/logs/bottle/checkpoints/model_final.pth
experiment_name: bottle
hidden_num: 128
latent_dim: 128
logging_root: DIF_decoder/eval
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 940
on_surface_points: 4000
point_cloud_path: datasets/sdf/bottle/eval/surface_pts_n_normal
steps_til_summary: 100