batch_size: 1
epochs: 50
epochs_til_checkpoint: 5
eval_split: DIF_decoder/split/eval/bowl.txt
checkpoint_path: DIF_decoder/logs/bowl/checkpoints/model_final.pth
experiment_name: bowl
hidden_num: 128
latent_dim: 128
logging_root: ./DIF_decoder/eval
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 801
on_surface_points: 4000
point_cloud_path: datasets/sdf/bowl/eval/surface_pts_n_normal
steps_til_summary: 100