batch_size: 10
epochs: 100
epochs_til_checkpoint: 5
expand: 0.02
experiment_name: mug
hidden_num: 128
latent_dim: 128
logging_root: DIF_decoder/logs
loss_correct: 50.0
loss_grad_deform: 5.0
loss_grad_temp: 100.0
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 3000
on_surface_points: 4000
point_cloud_path: datasets/sdf/mug/train/surface_pts_n_normal
steps_til_summary: 100
train_split: DIF_decoder/split/train/mug.txt